name: proyectoflutter_front
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icono.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/corazon_normal.gif
    - assets/images/corazon_recuperado.gif
    - assets/images/corazon_roto.gif
    - assets/images/fondo_cuervo.png
    - assets/images/fondo_ballena.png
    - assets/images/fondo_panda.png
    - assets/images/ballena_azul.png
    - assets/images/ballena_gris.png
    - assets/images/ballena_morada.png
    - assets/images/ballena_rosa.png
    - assets/images/cuervo_azul.png
    - assets/images/cuervo_gris.png
    - assets/images/cuervo_rosa.png
    - assets/images/cuervo_verde.png
    - assets/images/gato_azul.png
    - assets/images/gato_purpura.png
    - assets/images/gato_rosa.png
    - assets/images/gato_verde.png
    - assets/images/panda_azul.png
    - assets/images/panda_gris.png
    - assets/images/panda_rosa.png
    - assets/images/panda_verde.png 
    
